# Generated by Django 4.0.3 on 2022-09-20 13:10

import ckeditor.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campanha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campanha', models.CharField(max_length=128, verbose_name='Campanha')),
                ('descricao', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Descrição')),
                ('informacoes', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Informações Adicionais')),
                ('local', models.CharField(blank=True, max_length=128, null=True, verbose_name='Local')),
                ('contato1', models.CharField(blank=True, max_length=128, null=True, verbose_name='Celular')),
                ('contato2', models.CharField(blank=True, max_length=128, null=True, verbose_name='Telefone')),
                ('keyword', models.CharField(max_length=128, verbose_name='SEO')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('imagem', models.ImageField(upload_to=main.models.ImagemCampanha, validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])], verbose_name='Imagem (450x500)')),
            ],
            options={
                'verbose_name': 'Campanha',
                'verbose_name_plural': '5.1 - Campanhas',
            },
        ),
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128, verbose_name='Nome')),
                ('descricao', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Descrição')),
                ('url', models.CharField(blank=True, max_length=128, null=True, verbose_name='URL (Não alterar!)')),
                ('grupo', models.CharField(choices=[('Campanha', 'Campanha'), ('Collection', 'Collection')], max_length=64, verbose_name='Grupo')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('imagem', models.ImageField(upload_to=main.models.ImagemClasse, validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])], verbose_name='Imagem (450x500)')),
            ],
            options={
                'verbose_name': 'Classe',
                'verbose_name_plural': '5.0 - Classes',
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection', models.CharField(max_length=128, verbose_name='Collection')),
                ('descricao', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Descrição')),
                ('informacoes', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Informações Adicionais')),
                ('local', models.CharField(blank=True, max_length=128, null=True, verbose_name='Local')),
                ('contato1', models.CharField(blank=True, max_length=128, null=True, verbose_name='Celular')),
                ('contato2', models.CharField(blank=True, max_length=128, null=True, verbose_name='Telefone')),
                ('keyword', models.CharField(max_length=128, verbose_name='SEO')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('imagem', models.ImageField(upload_to=main.models.ImagemCollection, validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])], verbose_name='Imagem (450x500 ou Superior)')),
                ('grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.classes', verbose_name='Classe')),
            ],
            options={
                'verbose_name': 'Collection',
                'verbose_name_plural': '5.1 - Collections',
            },
        ),
        migrations.CreateModel(
            name='Conecta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publicacao', models.CharField(max_length=128, verbose_name='Publicação App Conecta')),
                ('descricao', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Descrição')),
                ('status', models.BooleanField(default=False, verbose_name='Status')),
                ('imagem', models.ImageField(upload_to=main.models.ImagemConecta, validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])], verbose_name='Imagem (420x520)')),
            ],
            options={
                'verbose_name': 'App Conecta',
                'verbose_name_plural': '2.0 - App Conecta',
            },
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=128, verbose_name='SEO')),
                ('descricao', models.CharField(blank=True, max_length=128, null=True, verbose_name='Descrição SEO')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'SEO',
                'verbose_name_plural': '1.0 - SEO',
            },
        ),
        migrations.CreateModel(
            name='Midia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('midia', models.CharField(max_length=128, verbose_name='Nome da Mídia')),
                ('url', models.URLField(max_length=512, verbose_name='URL da Mídia')),
                ('descricao', ckeditor.fields.RichTextField(blank=True, max_length=128, null=True, verbose_name='Descrição da Mídia')),
            ],
            options={
                'verbose_name': 'Webserie',
                'verbose_name_plural': '4.0 - Webseries',
            },
        ),
        migrations.CreateModel(
            name='Suporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suporte', models.CharField(max_length=128, verbose_name='Suporte')),
                ('telefone', models.CharField(blank=True, max_length=128, null=True, verbose_name='Telefone')),
                ('celular', models.CharField(blank=True, max_length=128, null=True, verbose_name='Celular')),
                ('email', models.EmailField(blank=True, max_length=64, null=True, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Canal de Suporte',
                'verbose_name_plural': '3.0 - Canais de Suporte',
            },
        ),
        migrations.CreateModel(
            name='ContatoCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=64, verbose_name='Nome Contato')),
                ('email', models.EmailField(max_length=64, verbose_name='Email Contato')),
                ('assunto', models.CharField(max_length=128, verbose_name='Assunto Contato')),
                ('mensagem', models.TextField(max_length=512, verbose_name='Mensagem Contato')),
                ('numero', models.CharField(blank=True, max_length=32, null=True, verbose_name='Numero Contato')),
                ('data_contato', models.DateTimeField(auto_now_add=True, verbose_name='Data Contato')),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.collection')),
            ],
            options={
                'verbose_name': 'Lead Collection',
                'verbose_name_plural': '5.2 - Lead Collections',
            },
        ),
        migrations.CreateModel(
            name='ContatoCampanha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=64, verbose_name='Nome Contato')),
                ('email', models.EmailField(max_length=64, verbose_name='Email Contato')),
                ('assunto', models.CharField(max_length=128, verbose_name='Assunto Contato')),
                ('mensagem', models.TextField(max_length=512, verbose_name='Mensagem Contato')),
                ('numero', models.CharField(blank=True, max_length=32, null=True, verbose_name='Numero Contato')),
                ('data_contato', models.DateTimeField(auto_now_add=True, verbose_name='Data Contato')),
                ('campanha', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.campanha')),
            ],
            options={
                'verbose_name': 'Lead Campanha',
                'verbose_name_plural': '5.2 - Lead Campanhas',
            },
        ),
        migrations.AddField(
            model_name='campanha',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.classes', verbose_name='Classe'),
        ),
    ]
